services:
  segment-db:
    image: postgres:17-alpine
    restart: always
    env_file: .env
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
      - ./infra/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}

  segment-test-db:
    image: postgres:17-alpine
    restart: always
    env_file: .env
    volumes:
      - ./tmp/pgdata_test:/var/lib/postgresql/data
      - ./infra/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}_test
      POSTGRES_PORT: ${POSTGRES_TEST_PORT}
